[package]
name = "entmoot"
authors = ["colemanirby <coleman@idealabs.network>"]
version = "0.1.0"
edition = "2024"
homepage = "https://idealabs.network"


[workspace]
resolver = "2"

[dependencies]
color-eyre = "0.6"
crossterm = "0.29"
ratatui = "0.29"
