[package]
name = "quickbeam"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
clap.workspace = true
fangorn.workspace = true
tokio.workspace = true
sp-core.workspace = true
secrecy.workspace = true
iroh.workspace = true
ark-std.workspace = true
rust-vault.workspace = true